### ISSUE TITLE
Initial Edits Needed to Run Successfully

### ISSUE THREAD

**Issue by acollow** [GEOS-ESM/QFED#11]
1. Support for "Final" MODIS files: NRT files for MODIS contain variable attributes for lat/lon that document the valid range for the files. This is missing from the final version of the MODIS files that would be used in a reanalysis framework. A code block already accounts for this in the VIIRS class which can be duplicated in the MODIS class.
2. Filepath to /ExtData is needed for the water mask
3. Species are hardwired into qfed_l3b.py, and not all species needed are included
4. frp.py gets tripped up and crashes if a file is corrupt.

**Comment by amdasilva** [comment]
Done.
