### ISSUE TITLE
QC Needs to Be Implemented for raw FRP data

### ISSUE THREAD

**Issue by acollow** [GEOS-ESM/QFED#13]
There are instances in which the raw FRP data for a single fire has a vastly negative FRP. This is getting into the gridded FRP product and results in negative emissions for a grid point. An example of this is in /css/viirs/data/Level2/VNP14IMG/2019/1VNP14IMG.A2019198.0136.001.2019198111726.nc.

**Comment by amdasilva** [comment]
Implemented by Allie.
